CREATE TABLE `cust_ref_db`.`master_customer_data`(
         `End Customer Global Ultimate Name` TEXT,
         `End Customer Global Ultimate Company Target ID` TEXT,
         `Qty of N9300 PIDs ordered` TEXT,
         `Qty of N9500 PIDs ordered` TEXT,
         `Qty of APIC PIDs ordered` TEXT,
         `Qty of C3 PIDs ordered` TEXT,
         `Qty of NFM PIDs ordered` TEXT,
         `Qty of Tetration PIDs ordered` TEXT,
         `Sales Agent Name` TEXT,
         `Assigned PSS` TEXT,
         `Assigned TSA` TEXT,
         `Reference Customer ?` TEXT,
         `Target as ACI to Production by end of Q1 ?` TEXT,
         `Equipment Status ?` TEXT,
         `Next Steps` TEXT,
         `Customer Vertical` TEXT,
         `Target for Competitive Pursuit ?` TEXT,
         `Other PSS` TEXT,
         `Sales Level 1` TEXT,
         `Sales Level 2` TEXT,
         `Sales Level 3` TEXT,
         `Sales Level 4` TEXT,
         `Sales Level 5` TEXT,
         `MultipleBookings` TEXT,
         `FirstDateBooked` TEXT,
         `LastDateBooked` TEXT, 
         `Last Refresh` TEXT
)
         