CREATE TABLE `cust_ref_db`.`master_bookings_data` (
    `Fiscal Year` TEXT,
    `Fiscal Quarter ID` TEXT,
    `Fiscal Period ID` TEXT,
    `Fiscal Week ID` TEXT,
    `Date Booked` TEXT,
    `Sales Level 1` TEXT,
    `Sales Level 2` TEXT,
    `Sales Level 3` TEXT,
    `Sales Level 4` TEXT,
    `Sales Level 5` TEXT,
    `Sales Level 6` TEXT,
    `Sales Agent Name` TEXT,
    `Internal Business Entity Name` TEXT,
    `Internal Sub Business Entity Name` TEXT,
    `Product Family` TEXT,
    `Product ID` TEXT,
    `End Customer Global Ultimate Name` TEXT,
    `End Customer Global Ultimate Company Target ID` TEXT,
    `Ship to ERP Customer Name` TEXT,
    `Sales Order Number Detail` TEXT,
    `ERP Deal ID` TEXT,
    `Corporate Bookings Flag` TEXT,
    `Partner Name` TEXT,
    `SCMS` TEXT,
    `Product Bookings Net` TEXT,
    `Service Bookings Net` TEXT,
    `Bookings Adjustments Description` TEXT ,
    `Hash Value` VARCHAR (32)
)	

