#
# [Source Column Name, Which SS/Excel sheet ?, Source Column Num, NEW Column name]
#
sheet_map = [['ERP End Customer Name', 'XLS_BOOKINGS', -1, 'Customer Name'],
             ['End Customer Global Ultimate Name', 'XLS_BOOKINGS', -1, 'Customer Alias'],
             ['pss', 'SS_COVERAGE', -1, 'PSS'],
             ['tsa', 'SS_COVERAGE', -1, 'TSA'],
             ['Sales Agent Name', 'XLS_BOOKINGS', -1, 'AM'],
             ['Project Manager', 'SS_AS', -1, 'AS PM'],
             ['AS Engineer 1', 'SS_AS', -1, 'AS CSE 1'],
             ['AS Engineer 2', 'SS_AS', -1, 'AS CSE 2'],
             ['Project Status/PM Completion', 'SS_AS', -1, 'AS Status'],
             ['Delivery Comments', 'SS_AS', -1, 'AS Comments'],
             ['Provisioning completed', 'SS_SAAS', -1, 'SAAS Status'],
             ['CSM', 'SS_CX', -1, 'CX Contact'],
             ['Comments', 'SS_CX', -1, 'CX Next Steps'],

             ['Start Date', 'XLS_SUBSCRIPTIONS', -1, 'Subscription Start', 'date'],
             ['Initial Term', 'XLS_SUBSCRIPTIONS', -1, 'Subscription Initial Term', 'int'],
             ['Renewal Date', 'XLS_SUBSCRIPTIONS', -1, 'Renewal Date', 'date'],
             ['Days Until Renewal', 'XLS_SUBSCRIPTIONS', -1, 'Days to Renewal', 'int'],
             ['Monthly Charge', 'XLS_SUBSCRIPTIONS', -1, 'Monthly Rev', 'currency'],
             ['Subscription ID', 'XLS_SUBSCRIPTIONS', -1, 'Subscription ID', 'text'],
             ['Status', 'XLS_SUBSCRIPTIONS', -1, 'Subscription Status', 'text'],
             ['Subscription Comments', '', -1, ''],


             ['PID', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS PID', 'text'],
             ['Delivery Manager', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS DM', 'text'],
             ['Delivery PM', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS PM', 'text'],
             ['Tracking status', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Status', 'text'],
             ['Tracking Sub-status', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS SubStatus', 'text'],
             ['Comments', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Comments', 'text'],
             ['Project Scheduled Start Date', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Start Date', 'date'],
             ['Scheduled End Date', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS End Date Scheduled', 'date'],
             ['Project Creation Date', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Creation Date', 'date'],
             ['Project Closed Date', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Close Date', 'date'],
             ['Traffic lights (account team)', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Traffic Lights', 'text'],
             ['Tracking Responsible', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Tracking Responsible', 'text'],
             ['ExecutiveSummary', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Exec Summary', 'text'],
             ['Critalpath', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Critical Path', 'text'],
             ['IsssuesRisks', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS IssuesRisks', 'text'],
             ['ActivitiesCurrent', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS Activities Current', 'text'],
             ['ActivitiesNext', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS ActivitiesNext', 'text'],
             ['LastUpdate', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS LastUpdate', 'text'],
             ['SO', 'XLS_AS_DELIVERY_STATUS', -1, 'NEW AS SO', 'text'],


             ['Orders Found', '', -1, ''],
             ['Total Bookings', 'XLS_BOOKINGS', -1, ''],
             ['Service Bookings', '', -1, ''],
             ['Product Type', 'SS_SKU', -1, '*DELETE*'],
             ['Bundle Product ID', 'XLS_BOOKINGS', -1, '*DELETE*'],
             ['Product Description', 'SS_SKU', -1, 'Platform Type'],
             ['Sensor Count', 'SS_SKU', -1, ''],
             ['Active Sensors', '', -1, ''],
             ['Sales Level 1', 'XLS_BOOKINGS', -1, ''],
             ['Sales Level 2', 'XLS_BOOKINGS', -1, ''],
             ['Sales Level 3', 'XLS_BOOKINGS', -1, ''],
             ['Sales Level 4', 'XLS_BOOKINGS', -1, ''],
             ['Sales Level 5', 'XLS_BOOKINGS', -1, ''],
             ['Sales Level 6', 'XLS_BOOKINGS', -1, '']]

sheet_keys = [['XLS_BOOKINGS', 'ERP End Customer Name', -1],
              # ['SS_CX', 'Account Name', -1],
              ['SS_CX', 'Customer', -1],
              ['SS_SAAS', 'Customer name', -1],
              ['SS_AS', 'Customer Name', -1]]
